apiVersion: lastest
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: andreatj/frontend
        name: frontend
        stdin_open: true
        tty: true
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  