apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://frontend-service:3000;
      }
      location /backend/ {
        proxy_pass http://backend-service:8080/;
      }
    }