- name: Ping Server for packet exchange
  ansible.builtin.ping:

- name: Bash Shell Response from Server
  shell: echo Hello from $(curl ifconfig.me)
  register: result

- name: Print Bash Response
  debug:
    var: result.stdout