all:
  children:
    localhost:
      hosts:
        {{ bastion_ip }}: #Bastion Server
    ci-cd-server:
      hosts:      
         {{ ci-cd_ip }}: #CI-CD Server 
    node-1:
      hosts:      
        {{ node-1_ip }}: #Node 1 
    node-2:
      hosts:
        {{ node-2_ip }}: #Node 2
    node-3:
      hosts:
        {{ node-3_ip }}: #Node 3
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu #username if using jenkins use jenkins
    ansible_ssh_private_key_file: '~/.ssh/bastion.pem' # copied private rsa key from the bastion server
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@18.135.124.208"' # ssh proxy for user@bastion-ip