- name: copy local ssh-key bastion
  become: true
  hosts: localhost
  roles:
  - sshkey-transfer

- name: install kubectl on the ci-cd server
  become: true
  hosts: ci-cd-server
  roles:
  - ping 
  - kubectl
  

- name: install kubectl on node-1
  become: true
  hosts: node-1
  roles:
  - ping 
  - kubectl


- name: install kubectl on node-2
  become: true
  hosts: node-2
  roles:
  - ping 
  - kubectl


- name: install kubectl on node-3
  become: true
  hosts: node-3
  roles:
  - ping 
  - kubectl