- name: install jenkins and kubectl
  become: true
  hosts: localhost
  roles:
  - kubectl
  - jenkins

- name: install kubectl
  become: true
  hosts: node-1
  roles:
  - kubectl

- name: install kubectl
  become: true
  hosts: node-2
  roles:
  - kubectl

- name: install kubectl
  become: true
  hosts: node-3
  roles:
  - kubectl